### ISSUE TITLE
Flatten Nested Components doesn't work: Wrong command line parameter(s) added

### ISSUE THREAD

**Issue by eweracs** [schriftgestalt/FontMakeExportPlugin#6]
Hello, clicking on the "Flatten Nested Components" parameter adds the line
`-f, --flatten-components`
This results in
`__main__.py: error: argument -f/--flatten-components: ignored explicit argument ','`

However, just using `-f` as the argument (as per the fontmake documentation) works.

**Comment by schriftgestalt** [comment]
Fixed it. But there are still some options that need additional input. The popup is more away to learn about the options than a one stop thing. So some editing by the user is expected.
