### ISSUE TITLE
Export Destination doesn't let me create a New Folder

### ISSUE THREAD

**Issue by anthrotype** [schriftgestalt/FontMakeExportPlugin#9]
The panel that opens up when I click on the Export Destination only allows one to select folders that already exist, but does not let one create a new folder and select that one.
Ideally one could create a new destination folder as well.

**Comment by schriftgestalt** [comment]
Thanks for finding this.
I fixed that in Glyphs (as the script uses API from the python wrapper). I don’t like to copy that code into plugin.
